version: '3'

services:
  db:
    container_name: db_service
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./database/mysql_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'crud_db'
      MYSQL_USER: 'axworkflow'
      MYSQL_PASSWORD: 'secret'
    networks:
      - axlaravelapi_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - axlaravelapi_network

  app:
    container_name: api_service
    tty: true
    image: docker.io/bitnami/laravel:8-debian-10
    environment:
      - DB_HOST=db
      - DB_USERNAME=axworkflow
      - DB_DATABASE=crud_db
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - 5000:3000
    volumes:
      - ./:/app
    networks:
      - axlaravelapi_network
    # privileged: true # Privileged mode could be required to run this container under Windows
networks:
  axlaravelapi_network:
volumes:
  mysql_db_data:
